name: tom_reflection_test
description: Tests for the tom_reflection standalone reflection generator.
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  tom_reflection:
    path: ../tom_reflection

dev_dependencies:
  build_runner: ^2.10.4
  tom_reflection_generator:
    path: ../tom_reflection_generator
  lints: ^6.0.0
  test: ^1.25.6
